//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Ciudad.SW {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ServiciosWebSoap", Namespace="http://tempuri.org/")]
    public partial class ServiciosWeb : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback IniciarSesionOperationCompleted;
        
        private System.Threading.SendOrPostCallback ObtenerSectoresOperationCompleted;
        
        private System.Threading.SendOrPostCallback ObtenerDenunciasOperationCompleted;
        
        private System.Threading.SendOrPostCallback bloquearDenunciaOperationCompleted;
        
        private System.Threading.SendOrPostCallback bloquearVideoOperationCompleted;
        
        private System.Threading.SendOrPostCallback cambiarContrasenaOperationCompleted;
        
        private System.Threading.SendOrPostCallback ObtenerReporteDenunciaOperationCompleted;
        
        private System.Threading.SendOrPostCallback ObtenerReporteVideosOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ServiciosWeb() {
            this.Url = global::Ciudad.Properties.Settings.Default.Ciudad_SW_ServiciosWeb;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event IniciarSesionCompletedEventHandler IniciarSesionCompleted;
        
        /// <remarks/>
        public event ObtenerSectoresCompletedEventHandler ObtenerSectoresCompleted;
        
        /// <remarks/>
        public event ObtenerDenunciasCompletedEventHandler ObtenerDenunciasCompleted;
        
        /// <remarks/>
        public event bloquearDenunciaCompletedEventHandler bloquearDenunciaCompleted;
        
        /// <remarks/>
        public event bloquearVideoCompletedEventHandler bloquearVideoCompleted;
        
        /// <remarks/>
        public event cambiarContrasenaCompletedEventHandler cambiarContrasenaCompleted;
        
        /// <remarks/>
        public event ObtenerReporteDenunciaCompletedEventHandler ObtenerReporteDenunciaCompleted;
        
        /// <remarks/>
        public event ObtenerReporteVideosCompletedEventHandler ObtenerReporteVideosCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IniciarSesion", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool IniciarSesion(string u, string p) {
            object[] results = this.Invoke("IniciarSesion", new object[] {
                        u,
                        p});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void IniciarSesionAsync(string u, string p) {
            this.IniciarSesionAsync(u, p, null);
        }
        
        /// <remarks/>
        public void IniciarSesionAsync(string u, string p, object userState) {
            if ((this.IniciarSesionOperationCompleted == null)) {
                this.IniciarSesionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnIniciarSesionOperationCompleted);
            }
            this.InvokeAsync("IniciarSesion", new object[] {
                        u,
                        p}, this.IniciarSesionOperationCompleted, userState);
        }
        
        private void OnIniciarSesionOperationCompleted(object arg) {
            if ((this.IniciarSesionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.IniciarSesionCompleted(this, new IniciarSesionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ObtenerSectores", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable ObtenerSectores() {
            object[] results = this.Invoke("ObtenerSectores", new object[0]);
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void ObtenerSectoresAsync() {
            this.ObtenerSectoresAsync(null);
        }
        
        /// <remarks/>
        public void ObtenerSectoresAsync(object userState) {
            if ((this.ObtenerSectoresOperationCompleted == null)) {
                this.ObtenerSectoresOperationCompleted = new System.Threading.SendOrPostCallback(this.OnObtenerSectoresOperationCompleted);
            }
            this.InvokeAsync("ObtenerSectores", new object[0], this.ObtenerSectoresOperationCompleted, userState);
        }
        
        private void OnObtenerSectoresOperationCompleted(object arg) {
            if ((this.ObtenerSectoresCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ObtenerSectoresCompleted(this, new ObtenerSectoresCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ObtenerDenuncias", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable ObtenerDenuncias() {
            object[] results = this.Invoke("ObtenerDenuncias", new object[0]);
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void ObtenerDenunciasAsync() {
            this.ObtenerDenunciasAsync(null);
        }
        
        /// <remarks/>
        public void ObtenerDenunciasAsync(object userState) {
            if ((this.ObtenerDenunciasOperationCompleted == null)) {
                this.ObtenerDenunciasOperationCompleted = new System.Threading.SendOrPostCallback(this.OnObtenerDenunciasOperationCompleted);
            }
            this.InvokeAsync("ObtenerDenuncias", new object[0], this.ObtenerDenunciasOperationCompleted, userState);
        }
        
        private void OnObtenerDenunciasOperationCompleted(object arg) {
            if ((this.ObtenerDenunciasCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ObtenerDenunciasCompleted(this, new ObtenerDenunciasCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/bloquearDenuncia", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool bloquearDenuncia(int id) {
            object[] results = this.Invoke("bloquearDenuncia", new object[] {
                        id});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void bloquearDenunciaAsync(int id) {
            this.bloquearDenunciaAsync(id, null);
        }
        
        /// <remarks/>
        public void bloquearDenunciaAsync(int id, object userState) {
            if ((this.bloquearDenunciaOperationCompleted == null)) {
                this.bloquearDenunciaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnbloquearDenunciaOperationCompleted);
            }
            this.InvokeAsync("bloquearDenuncia", new object[] {
                        id}, this.bloquearDenunciaOperationCompleted, userState);
        }
        
        private void OnbloquearDenunciaOperationCompleted(object arg) {
            if ((this.bloquearDenunciaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.bloquearDenunciaCompleted(this, new bloquearDenunciaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/bloquearVideo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool bloquearVideo(int id) {
            object[] results = this.Invoke("bloquearVideo", new object[] {
                        id});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void bloquearVideoAsync(int id) {
            this.bloquearVideoAsync(id, null);
        }
        
        /// <remarks/>
        public void bloquearVideoAsync(int id, object userState) {
            if ((this.bloquearVideoOperationCompleted == null)) {
                this.bloquearVideoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnbloquearVideoOperationCompleted);
            }
            this.InvokeAsync("bloquearVideo", new object[] {
                        id}, this.bloquearVideoOperationCompleted, userState);
        }
        
        private void OnbloquearVideoOperationCompleted(object arg) {
            if ((this.bloquearVideoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.bloquearVideoCompleted(this, new bloquearVideoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/cambiarContrasena", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool cambiarContrasena(string usern, string pactual, string pn1, string pn2) {
            object[] results = this.Invoke("cambiarContrasena", new object[] {
                        usern,
                        pactual,
                        pn1,
                        pn2});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void cambiarContrasenaAsync(string usern, string pactual, string pn1, string pn2) {
            this.cambiarContrasenaAsync(usern, pactual, pn1, pn2, null);
        }
        
        /// <remarks/>
        public void cambiarContrasenaAsync(string usern, string pactual, string pn1, string pn2, object userState) {
            if ((this.cambiarContrasenaOperationCompleted == null)) {
                this.cambiarContrasenaOperationCompleted = new System.Threading.SendOrPostCallback(this.OncambiarContrasenaOperationCompleted);
            }
            this.InvokeAsync("cambiarContrasena", new object[] {
                        usern,
                        pactual,
                        pn1,
                        pn2}, this.cambiarContrasenaOperationCompleted, userState);
        }
        
        private void OncambiarContrasenaOperationCompleted(object arg) {
            if ((this.cambiarContrasenaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.cambiarContrasenaCompleted(this, new cambiarContrasenaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ObtenerReporteDenuncia", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable ObtenerReporteDenuncia() {
            object[] results = this.Invoke("ObtenerReporteDenuncia", new object[0]);
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void ObtenerReporteDenunciaAsync() {
            this.ObtenerReporteDenunciaAsync(null);
        }
        
        /// <remarks/>
        public void ObtenerReporteDenunciaAsync(object userState) {
            if ((this.ObtenerReporteDenunciaOperationCompleted == null)) {
                this.ObtenerReporteDenunciaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnObtenerReporteDenunciaOperationCompleted);
            }
            this.InvokeAsync("ObtenerReporteDenuncia", new object[0], this.ObtenerReporteDenunciaOperationCompleted, userState);
        }
        
        private void OnObtenerReporteDenunciaOperationCompleted(object arg) {
            if ((this.ObtenerReporteDenunciaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ObtenerReporteDenunciaCompleted(this, new ObtenerReporteDenunciaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ObtenerReporteVideos", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable ObtenerReporteVideos() {
            object[] results = this.Invoke("ObtenerReporteVideos", new object[0]);
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void ObtenerReporteVideosAsync() {
            this.ObtenerReporteVideosAsync(null);
        }
        
        /// <remarks/>
        public void ObtenerReporteVideosAsync(object userState) {
            if ((this.ObtenerReporteVideosOperationCompleted == null)) {
                this.ObtenerReporteVideosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnObtenerReporteVideosOperationCompleted);
            }
            this.InvokeAsync("ObtenerReporteVideos", new object[0], this.ObtenerReporteVideosOperationCompleted, userState);
        }
        
        private void OnObtenerReporteVideosOperationCompleted(object arg) {
            if ((this.ObtenerReporteVideosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ObtenerReporteVideosCompleted(this, new ObtenerReporteVideosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    public delegate void IniciarSesionCompletedEventHandler(object sender, IniciarSesionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IniciarSesionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal IniciarSesionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    public delegate void ObtenerSectoresCompletedEventHandler(object sender, ObtenerSectoresCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ObtenerSectoresCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ObtenerSectoresCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    public delegate void ObtenerDenunciasCompletedEventHandler(object sender, ObtenerDenunciasCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ObtenerDenunciasCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ObtenerDenunciasCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    public delegate void bloquearDenunciaCompletedEventHandler(object sender, bloquearDenunciaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class bloquearDenunciaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal bloquearDenunciaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    public delegate void bloquearVideoCompletedEventHandler(object sender, bloquearVideoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class bloquearVideoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal bloquearVideoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    public delegate void cambiarContrasenaCompletedEventHandler(object sender, cambiarContrasenaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class cambiarContrasenaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal cambiarContrasenaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    public delegate void ObtenerReporteDenunciaCompletedEventHandler(object sender, ObtenerReporteDenunciaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ObtenerReporteDenunciaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ObtenerReporteDenunciaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    public delegate void ObtenerReporteVideosCompletedEventHandler(object sender, ObtenerReporteVideosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ObtenerReporteVideosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ObtenerReporteVideosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591